# Generated by Django 4.2.6 on 2023-10-05 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='media_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('description', models.TextField()),
                ('Image', models.ImageField(upload_to='post/images')),
                ('shortname', models.SlugField(max_length=255, unique=True)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('cast', models.TextField()),
                ('video_url', models.CharField(blank=True, max_length=250)),
                ('movie_genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='genre_category', to='Posts.genre')),
                ('movie_media_genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mediagenre_category', to='Posts.media_genre')),
            ],
        ),
    ]
