# Generated by Django 4.2.6 on 2023-10-08 15:29

# from django.db import migrations
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('Posts', '0001_initial'),
#     ]
#
#     operations = [
#     ]


from django.db import migrations
from django.contrib.auth.models import Group

def create_groups(apps, schema_editor):
    subscribers_group, created = Group.objects.get_or_create(name='subscribers')
    content_creators_group, created = Group.objects.get_or_create(name='content_creators')

class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
