# Generated by Django 4.2.6 on 2023-10-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_userfavorite_delete_userfavoritemovie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFavorite',
        ),
    ]
